### ISSUE TITLE
关于奖励函数结果曲线

### ISSUE THREAD

**Issue by wyz1074152339** [kaixindelele/DRL-tensorflow#1]
你好，我用您的程序跑了下，画出了300次后的曲线，我想问的是奖励从负数稳定在0 附近，请问为什么奖励没有朝着正数发展呢，可以添加您的微信或者QQ交流吗

**Comment by kaixindelele** [comment]
能贴一下代码吗？我不知道你跑的是什么环境，什么算法。可以加深度强化学习-DRL群799378128

**Comment by wyz1074152339** [comment]
感谢大神的回复，我已经添加您推荐的群了，问题知道原因了，因为gym环境Pendulum-v0的奖励一直是负数，最小-16点几，最大是0, 所以说奖励函数曲线没有大于0的情况。
另外大神，能否告知您的文件夹里的sac-auto（子文件夹sac-auto-class, sac-auto-per-class）和sac-sp子文件夹里的文件都是什么意思嘛，我看的有点混乱，谢谢！

**Comment by kaixindelele** [comment]
文件命名示例：
sac_sp.py：凡是带下划线sp的文件，都是spinup中的封装形式，即把强化算法封装成函数；
sac_class.py 凡是带class的文件，都是封装成类的形式，便于大家直接调用；
sac_auto_per_class 凡是带per的文件，都是可以选择是否调用优先经验回放的class，但是有时候优先经验回放并不一定好使。
另外关于sac_auto，也被称作sac2，或者自适应sac，因为alpha超参数是放到网络中进行学习，一般来说要比sac更容易调用。

我已经更新到readme中了，感谢反馈~

**Comment by wyz1074152339** [comment]
恢复好及时，感谢！
